name:  Run unit tests with nose 

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting (simulated with echo)
        run: echo "Running linting step..."

  test:
    runs-on: ubuntu-latest
    needs: lint  # This ensures that 'test' runs after 'lint'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests (simulated with echo)
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures that 'deploy' runs after 'test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy (simulated with echo)
        run: echo "Deploying application..."
